### ISSUE TITLE
The question to Anatomical_Mask.nii.gz 

### ISSUE THREAD

**Issue by ShangWeiKuo** [UCSB-VRL/NPH_Prediction#10]
Excuse me. 

Is **Anatomical_Mask.nii.gz** the anatomical ventricular region based on anatomical prior knowledge of the average ventricle location in MNI152 space?

If not, how can I do to generate Anatomical_Mask.nii.gz?

**Comment by unimusic** [comment]
Correct, you can generate your own or use the one provided.
