### ISSUE TITLE
What is the method of thresholding?

### ISSUE THREAD

**Issue by ShangWeiKuo** [UCSB-VRL/NPH_Prediction#11]
Excuse me. In the article, there is a paragraph stated that the first step of your data preprocessing is extracting skull of each scan by **thresholding**. However, I haven't found the proper noun and theory of the thresholding method in your article.

Later, I studied the file CTtools.py and found the function named **bone_extracted**. Is this function your thresholding methods mentioned in your article? What is the statistical theory making you decide to set bone_pixel as 500?

**Comment by unimusic** [comment]
The intensity level of bone is pretty standard in CT images. For the skull, we found that a threshold of 500 was effective for the images we had. You can adjust this if you like.
