### ISSUE TITLE
module ipdb not in requirements

### ISSUE THREAD

**Issue by muschellij2** [UCSB-VRL/NPH_Prediction#2]
https://github.com/UCSB-VRL/NPH_Prediction/blob/master/nph_prediction.py#L47 has the line for ipdb, but not in `requirements.txt`

**Comment by unimusic** [comment]
Removed. Thanks

**Comment by muschellij2** [comment]
FYI also at https://github.com/UCSB-VRL/NPH_Prediction/blob/master/MNI2CTAffine.py#L8

**Comment by unimusic** [comment]
Oops, also removed. Thank you.
