### ISSUE TITLE
ENH: Move 152 out

### ISSUE THREAD

**Issue by muschellij2** [UCSB-VRL/NPH_Prediction#3]
So after running, the `Scans` directory is now changed so that these files are added
```
CT000025_MNI152.nii.gz
CT000025_affine.mat
CT000025_skull.nii
```
I think having these put into another folder, such as `MNI152` and then probably removing `CT000025_skull.nii` would make the most sense.  Also, probably appending to `volumes.csv` and `predictions_rbf_svm.csv` if they exist (I'm not sure if you do given https://github.com/UCSB-VRL/NPH_Prediction/blob/master/postUtils.py#L59) would be beneficial as if you deleted.

Also, probably deleting 
```
imname_affine1.pkl
imname_header1.pkl
imname_list1.pkl
imname_affine.pkl
imname_header.pkl
imname_list.pkl
```
after running would be helpful as well. 

Looks like an interesting model and hope to try to work with it in the future!

**Comment by unimusic** [comment]
That's a good idea, I added saving previous results as an option. The organizational suggestions are also well taken.
