### ISSUE TITLE
The Error message: _pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by ShangWeiKuo** [UCSB-VRL/NPH_Prediction#7]
Excuse me. 

When I run the line 118 "checkpoint = torch.load(model_file, map_location=torch.device(device))" in **unetSeg.py**, I got the error message: "_pickle.UnpicklingError: invalid load key, 'v'.".

Therefore, could you share with your solution to deal with the problem with loading tar extension file ?

**Comment by unimusic** [comment]
I'm sorry you're dealing with this issue. Which branch of the code are you using?

**Comment by unimusic** [comment]
Can you provide a runtime example?

**Comment by ShangWeiKuo** [comment]
Good afternoon, I got the error message when I cloned the project and implemented the command "git clone ... " in the beginning. 

However, I dealt with the problem when I changed the command from "git clone ... " to "git-lfs clone ... ". 

Apologies for my late reply.
