### ISSUE TITLE
The problem happened when using mcv model

### ISSUE THREAD

**Issue by ShangWeiKuo** [UCSB-VRL/NPH_Prediction#8]
Excuse me. When I ran mcv model to conduct segmentation, I met problems that were lack of files whose filenames including "_affine.mat" and "_MNI152.nii.gz". How do I generate those files to ran mcv model smoothly?

Thanks for your reply last week, and I appreciate you for your reply.

**Comment by unimusic** [comment]
Hi there, can you please include the branch of code you are using from the repo, and also what exactly you tried to run? Thanks.

**Comment by ShangWeiKuo** [comment]
Thank you for your reply. This picture below is the problem I met yesturday. <br>
It seems that there should be two kinds of data with filenames including "_affine.mat" and "_MNI152.nii.gz" in Scans. However, I cannot find out such filenames in Scans. <br>
By the way, Scans3 is new directory I created, and it contains two data which is from CQ500 dataset.
<br>
![image](https://user-images.githubusercontent.com/26018604/191143992-9df7d71f-ae37-4f16-9102-58dcc58b6793.png)

**Comment by unimusic** [comment]
Oh I see, thanks. It seems like the registration step failed. Have you installed FSL?

**Comment by ShangWeiKuo** [comment]
I'm installing FSL. Do you means that files including "_affine.mat" and "_MNI152.nii.gz" will be generated when I run "python3 nph_prediction.py --seg=mcv" on FSL ?

**Comment by unimusic** [comment]
If you have properly installed FSL and your images are of good quality, then yes, it should generate those files when you run the python code. You don't need to call FSL directly.

**Comment by ShangWeiKuo** [comment]
It works! Thank you for your guidance.
